/*
 * DSPRE Script File
 * Rom ID: Pokemon-Spectral-Dream-v2
 * Game: HGSS
 * File: 0228
 * Generated: 9/03/2026 8:33:00 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 109
	JumpIf EQUAL Function#1
	Message 0
	SetVar 0x8004 468
	SetVar 0x8005 1
	CommonScript 2033
	SetFlag 109
	SetVar 0x408C 1
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
