/*
 * DSPRE Script File
 * Rom ID: Pokemon-Spectral-Dream-v2
 * Game: HGSS
 * File: 0254
 * Generated: 9/03/2026 8:33:00 PM
 */

//===== SCRIPTS =====//
Script 1:
End

Script 2:
	SetIconBoard 18 1 3 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 3:
	SetTextBoard 3 0
	ShowBoard 3
	WaitBoard
	BoardMessage 19 0x800C
	CommonScript 2000
End

Script 4:
	SetIconBoard 20 1 6 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
