/*
 * DSPRE Script File
 * Rom ID: Pokemon-Spectral-Dream-v2
 * Game: HGSS
 * File: 0960
 * Generated: 9/03/2026 8:33:01 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 0 0x800C
	CommonScript 2000
End

Script 2:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 1 0x800C
	CommonScript 2000
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
