/*
 * DSPRE Script File
 * Rom ID: Pokemon-Spectral-Dream
 * Game: HGSS
 * File: 0844
 * Generated: 16/12/2025 8:40:53 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	TextPlayerName 0
	GenderMessage 0 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
