/*
 * DSPRE Script File
 * Rom ID: Pokemon-Spectral-Dream
 * Game: HGSS
 * File: 0006
 * Generated: 16/12/2025 8:40:51 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetFlag 394
	Message 1
	FreezeMessage
	SetVar 0x8004 27
	CommonScript 2052
	ClearFlag 394
	ReleaseAll
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
