/*
 * DSPRE Script File
 * Rom ID: Pokemon-Spectral-Dream
 * Game: HGSS
 * File: 0836
 * Generated: 16/12/2025 8:40:53 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	Movement Player Action#1
	WaitMovement
	PlayFanfare SEQ_SE_GS_N_LINEAR
	WaitTime 40 0x8004
	StopFanfare SEQ_SE_GS_N_LINEAR
	CMD_722 1 1 198 17 11
	SetVar 0x411E 0
	ReleaseAll
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
Action 1:
	WalkWest8 0x7
	WalkNorth8 0x2
End

