/*
 * DSPRE Script File
 * Rom ID: Heart-Gold-v0-1
 * Game: HGSS
 * File: 0006
 * Generated: 25/02/2026 12:44:43 AM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetFlag 394
	Message 1
	FreezeMessage
	SetVar 0x8004 27
	CommonScript 2052
	ClearFlag 394
	ReleaseAll
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
