/*
 * DSPRE Script File
 * Rom ID: Heart-Gold-v0-1
 * Game: HGSS
 * File: 0254
 * Generated: 25/02/2026 12:44:44 AM
 */

//===== SCRIPTS =====//
Script 1:
End

Script 2:
	SetIconBoard 18 1 3 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

Script 3:
	SetTextBoard 3 0
	ShowBoard 3
	WaitBoard
	BoardMessage 19 0x800C
	CommonScript 2000
End

Script 4:
	SetIconBoard 20 1 6 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
