/*
 * DSPRE Script File
 * Rom ID: Heart-Gold-v0-1
 * Game: HGSS
 * File: 0751
 * Generated: 25/02/2026 12:44:45 AM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CommonScript 2011
	FreezeMessage
	SetVar 0x8004 25
	CommonScript 2052
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CommonScript 2011
	FreezeMessage
	SetVar 0x8004 1
	CommonScript 2048
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
