/*
 * DSPRE Script File
 * Rom ID: Heart-Gold-v0-0
 * Game: HGSS
 * File: 0006
 * Generated: 26/02/2026 11:41:53 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	SetFlag 394
	Message 1
	FreezeMessage
	SetVar 0x8004 27
	CommonScript 2052
	ClearFlag 394
	ReleaseAll
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
