/*
 * DSPRE Script File
 * Rom ID: Heart-Gold-v0-0
 * Game: HGSS
 * File: 0082
 * Generated: 26/02/2026 11:41:53 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CommonScript 0x28C8
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CommonScript 0x28C9
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CommonScript 0x28CA
	ReleaseAll
End

Script 4:
	SetVar 0x40E5 2
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
