/*
 * DSPRE Script File
 * Rom ID: Heart-Gold-v0-0
 * Game: HGSS
 * File: 0198
 * Generated: 26/02/2026 11:41:54 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetVar 0x4085 0
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 249
	JumpIf EQUAL Function#1
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 1
Jump Function#2

Function 2:
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
