/*
 * DSPRE Script File
 * Rom ID: Heart-Gold-v0-0
 * Game: HGSS
 * File: 0200
 * Generated: 26/02/2026 11:41:54 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	GetItemQuantity ITEM_SUPER_ROD 0x800C
	CompareVarValue 0x800C 0
	JumpIf DIFFERENT Function#1
	Message 0
	OpenTouchScreen
	YesNoTouchScreen 0x800C
	CloseTouchScreen
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#2
	Message 1
	SetVar 0x8004 447
	SetVar 0x8005 1
	CommonScript 2033
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Function 2:
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
