/*
 * DSPRE Script File
 * Rom ID: Heart-Gold-v0-0
 * Game: HGSS
 * File: 0257
 * Generated: 26/02/2026 11:41:54 PM
 */

//===== SCRIPTS =====//
Script 1:
End

Script 2:
	SetTextBoard 2 0
	ShowBoard 3
	WaitBoard
	BoardMessage 0 0x800C
	CommonScript 2000
End

Script 3:
	SetIconBoard 1 1 1 0x800C
	ShowBoard 3
	WaitBoard
	CloseBoard 0x800C
	CommonScript 2000
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
