/*
 * DSPRE Script File
 * Rom ID: Heart-Gold-v0-0
 * Game: HGSS
 * File: 0779
 * Generated: 26/02/2026 11:41:55 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetVar 0x8007 0
	CommonScript 2002
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckFlag 371
	JumpIf EQUAL Function#1
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 3
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
