/*
 * DSPRE Script File
 * Rom ID: Heart-Gold-v0-0
 * Game: HGSS
 * File: 0959
 * Generated: 26/02/2026 11:41:55 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	CheckBadge 14 0x800C
	CompareVarValue 0x800C 1
	JumpIf EQUAL Function#1
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
