/*
 * DSPRE Script File
 * Rom ID: Pokemon-Spectral-Dream-v1
 * Game: HGSS
 * File: 0078
 * Generated: 8/03/2026 9:40:20 PM
 */

//===== SCRIPTS =====//
Script 1:
	SetVar 0x8007 0
	CommonScript 2002
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 4:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 5:
	SetVar 0x40E5 2
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
