/*
 * DSPRE Script File
 * Rom ID: Pokemon-Spectral-Dream-v1
 * Game: HGSS
 * File: 0756
 * Generated: 8/03/2026 9:40:22 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	PlayCry SPECIES_NIDORAN♂ 0
	Message 1
	WaitCry
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
