/*
 * DSPRE Script File
 * Rom ID: Heart-Gold-v0-2
 * Game: HGSS
 * File: 0062
 * Generated: 8/03/2026 9:17:41 PM
 */

//===== SCRIPTS =====//
Script 1:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 0
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	FacePlayer
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

Script 3:
	SetVar 0x4125 0
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
