/*
 * DSPRE Script File
 * Rom ID: Heart-Gold-v0-2
 * Game: HGSS
 * File: 0846
 * Generated: 8/03/2026 9:17:43 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	PlayFanfare SEQ_SE_DP_PC_ON
	TextPlayerName 0
	Message 0
	CloseMessage
	CountMail 0x800C
	CompareVarValue 0x800C 0
	JumpIf EQUAL Function#1
	FadeScreen 6 1 0 0
	WaitFadeScreen
	MailScreen
	ReturnScreen
	FadeScreen 6 1 1 0
	WaitFadeScreen
	ReleaseAll
End

Script 2:
	PlayFanfare SEQ_SE_CONFIRM
	LockAll
	Message 2
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== FUNCTIONS =====//
Function 1:
	Message 1
	WaitButton
	CloseMessage
	ReleaseAll
End

//===== ACTIONS =====//
