/*
 * DSPRE Script File
 * Rom ID: Heart-Gold-v0-2
 * Game: HGSS
 * File: 0895
 * Generated: 8/03/2026 9:17:43 PM
 */

//===== SCRIPTS =====//
Script 1:
	MecScript
	LockAll
	Movement Player Action#1
	WaitMovement
	PlayFanfare SEQ_SE_GS_N_LINEAR
	WaitTime 40 0x8004
	StopFanfare SEQ_SE_GS_N_LINEAR
	CMD_722 0 1 401 14 11
	SetVar 0x411F 0
	ReleaseAll
End

//===== FUNCTIONS =====//
//===== ACTIONS =====//
Action 1:
	WalkEast8 0x7
	WalkNorth8 0x2
End

